name: Generate SVGs Daily 
# 由於他的svg都不會保存資料，每次同步upstream/master都會不見，然後她的action貌似除取得data其他都沒有用，所以自己補上

on:
  schedule:
    - cron: "0 2 * * *"   # 台北時間 每天 10:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set current year variable
        run: echo "YEAR=$(date +%Y)" >> $GITHUB_ENV
      
      # 生成圖片
      - name: Run scripts
        run: |
          python run_page/gen_svg.py --from-db --title "Over 1km Runs" --type grid --athlete "Gray" --output assets/grid.svg --special-color yellow --special-color2 red --special-distance 10 --special-distance2 20 --use-localtime --min-distance 1
          python run_page/gen_svg.py --from-db --type monthoflife --birth "1997-02" --special-color "#f9d367" --special-color2 "#f0a1a8" --output assets/mol_running.svg --use-localtime --athlete "Gray" --title "Runner Month of Life" --sport-type running
          python run_page/gen_svg.py --from-db --year $YEAR --language zh_CN --title "${YEAR} Running" --type github --github-style "align-firstday" --athlete "Gray" --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github_${YEAR}.svg --use-localtime --min-distance 1
          python run_page/gen_svg.py --from-db --type year_summary --output assets/year_summary.svg --athlete "Gray"
          python run_page/gen_svg.py --from-db --type circular --use-localtime
          python run_page/gen_svg.py --from-db --title "Gray Running" --type github --github-style "align-firstday" --athlete "Gray" --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github.svg --use-localtime --min-distance 1
      
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update SVG generated files"
            git push
          else
            echo "No changes to commit"
          fi